### PR TITLE
adding jabber protocol

### PR DESCRIPTION
**Pull request by nassimabedi**

### CODE REVIEW

**Comment by nassimabedi** [comment]
adding jabber protocol

**Comment by nassimabedi** [comment]
Would you please describe about Coverage decreased.
This pull request works on my laptop!

**Comment by nikofil** [comment]
Nice work! If you can add a pcap file with some jabber flows, along with the expected number of flows to https://github.com/mushorg/go-dpi/blob/master/modules/classifiers/classifiers_test.go#L143, that should fix the coverage issue.
Also, could you run `go fmt $(go list ./... | grep -v /vendor/)` and see if there are formatting issues? Because I see e.g. in a couple places spaces instead of tabs.

**Comment by nassimabedi** [comment]
Thank you for your guidance  :slightly_smiling_face:
My result is different:
This is my result:
`Number of packets: 24
Number of packets identified: 13
Protocols identified:
 map[JABBER:10 DNS:3]`
Also my results is different from the classifier_test in other protocols?!

**Comment by nikofil** [comment]
No, that's okay, the tests count flows while the app counts the individual packets. :)

**Pull request merged**
