### PR TITLE
Additional classifiers

### PR DESCRIPTION
**Pull request by Perseus**
Added classifiers for

- Git
- Telegram
- Hangouts

### CODE REVIEW

**Comment by glaslos** [comment]
For the future, make sure you branch first before making changes.

**Comment by glaslos** [comment]
Can you also add some test? You might be able to find pcaps for the added protocols here: https://wiki.wireshark.org/SampleCaptures

**Comment by Perseus** [comment]
@glaslos Yeah, I did make a branch but while trying to change the fork/repo thing from the earlier issue and trying to make sure my master was up to date to pass the tests I merged it into my master by mistake. 
Will take care from next time.

**Comment by nikofil** [comment]
Thank you for your PR! :)
We are aiming for this library to be port-independent (should probably say that in the README), I put the ports in for the other protocols for now in order for the library to work but I plan on removing them soon. So could you please make sure that your classifiers can also work without ports?
Besides that, it would be nice to have the protocols also supported by the nDPI and libprotoident wrappers. I see that both libraries support the protocols, so it would be just a matter of adding the mapping from the library code to the go-dpi Protocol. It's simple, but you can see "Adding a mapping from a wrapper to the protocol" in https://docs.google.com/document/d/13WLV7QYLERwAWNTYajvywaOYXeBq5Rk3YR-Rl65S0WU/edit?usp=sharing for details (I'll port this doc to the wiki shortly).

**Comment by Perseus** [comment]
The classifiers I wrote were basically golang translations of the respective ndpi classifiers. Would you rather that I just create ndpi wrappers instead?

**Comment by nikofil** [comment]
If they do the exact same checks then yes, that would be better, since we already have a wrapper for nDPI, we might as well let them do our job for us. Maybe we can keep some very simple checks in the wrappers, so that we don't have to ask nDPI every time. However, I don't know how much simpler we can go than this, before starting to lose precision because of the wrappers misclassifying things.
I would also like to know @glaslos input on this.

**Comment by glaslos** [comment]
The idea of the go-dpi layer was to make a decision faster than using the wrappers. I think it would also make sense to keep the number of packets required for the go-dpi layer as low as possible. We could implement the go-dpi layer with the idea that it is fast, requires only one packet but might cause false positives/miss classifications. So if you want to be more precise, you should add at least one of the wrappers.

**Comment by Perseus** [comment]
@glaslos Wouldn't the number of packets being analyzed by the go-dpi layer differ from classifier to classifier? Example would be I guess HTTP (a couple packets should be enough, I think?), SSL( needs more to confirm the 3-way handshake or certificates, otherwise could result in a false negative ).

@nikofil Alright, I'll create wrappers around nDPI for them then. Should I close this PR?

**Comment by nikofil** [comment]
False negatives aren't as big an issue, we can then go to the next layer. That doesn't mean we should only look at one packet in all cases, just that we try to do the minimal work with heuristics.
SSL is kind of a special case, especially because it might encapsulate other protocols (HTTPS etc) but we haven't really gotten around to that.
You can update this PR or make another one, whatever you wish.

**Comment by glaslos** [comment]
Closing this for now.

**Pull request closed without merging**
